### ISSUE TITLE
can't find `ftop`

### ISSUE THREAD

**Issue by Jeff-Walker** [ranger6/ca#1]
In `pubcert` you're using `ftop`. I don't have that and I'm having trouble finding it. It seems to be a `top` like tool for files, but I'm not understanding what you're using it for. The script says "look for fqdn and convert to path expression", but I'm not sure how `ftop` could help with that.

I'm willing find another way to do it, but I'm not sure what's going on exactly.

**Comment by Jeff-Walker** [comment]
Missed the description of `ftop` and `urlencode`.

**Comment by ranger6** [comment]
Indeed, long into the README, the dependence on ftop and urlencode is described.  That is, it is too far down for someone to start reading and following the example successfully.

An earlier section in the README should describe the download and installation process for this project plus the two tools needed to make everything work.

**Comment by ranger6** [comment]
Fixed with PR fa74621

**Comment by Jeff-Walker** [comment]
Cool. Yes that was problem.

Not 100% related to `ftop`, but rather using the output, but my openssl reports the subject as

> $ cert -cn certs/AGT.rootCA.cert.pem
> subject=C = US, ST = Tennessee, L = Memphis, O = USPS, OU = AGT, CN = AGT.rootCA, emailAddress = jeffery.d.walker@usps.gov

Which threw off your `sed` patterns. I'll fix that myself and if I can figure out which version that changed in I'll submit a PR unless you fix it first. Or I'll come up with a regex that does both.

My version:
 > $ openssl version
 > OpenSSL 1.1.1f  31 Mar 2020
